### ISSUE TITLE
text autocomplete  very slow when I install mape-Helpers

### ISSUE THREAD

**Issue by xueqing0622** [mape/ComfyUI-mape-Helpers#12]
[mape-Helpers] is a very talent and useful extension.
but text autocomplete  very slow when I install mape-Helpers.
![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/114840118/230a73c1-1c95-45ea-94ba-b19e3651b266)
hope can fixed this! 
have a nice day

**Comment by mape** [comment]
Have you tried the fix mentioned here: https://github.com/mape/ComfyUI-mape-Helpers/issues/8 ?

**Comment by xueqing0622** [comment]
It works , thx!
