### ISSUE TITLE
Disappearing commas in the "Floating prompt tweak window"

### ISSUE THREAD

**Issue by hben35096** [mape/ComfyUI-mape-Helpers#13]
Hello, this plugin has brought me some pleasant surprises, particularly "Floating prompt tweak window." Comfyui has never had a satisfactory prompt tool, hence my continued parallel use of sd_webui, which offers a plugin:

https://github.com/Physton/sd-webui-prompt-all-in-one

This plugin is indispensable for prompt editing, introducing an abundance of conveniences. In our country, virtually all users of AUTOMATIC1111 sd_webui rely on this plugin.

The emergence of "mape-Helpers" has given me cause for optimism. However, several issues persist, such as disappearing commas between phrases, an unpredictable function of the "NORMALIZE" button, and the apparent inability to temporarily disable a specific prompt (useful for testing the impact of a particular prompt). Integrating all the features of "all-in-one" into "Floating prompt tweak window" might be wishful thinking, yet I still eagerly anticipate further advancements in prompt editing from this plugin.

**Comment by mape** [comment]
Do you have a sample prompt that reproduces the issue?

**Comment by hben35096** [comment]
![PixPin_2024-04-07_15-45-55](https://github.com/mape/ComfyUI-mape-Helpers/assets/139383150/198574a6-173c-4513-a573-c80c32268145)

**Comment by mape** [comment]
What you are seeing after changing the weights is the serialized output coming from the SD Prompt Parser. 
Unless this causes differences in the generated output it is unlikely to change.
