### ISSUE TITLE
 Your plugin cannot work properly with the image picker plugin. Can it be fixed?

### ISSUE THREAD

**Issue by wibur0620** [mape/ComfyUI-mape-Helpers#17]
https://github.com/mape/ComfyUI-mape-Helpers/assets/131615326/5e63d587-9bb3-44e8-913e-dd57329bd034

**Comment by wibur0620** [comment]
https://github.com/chrisgoringe/cg-image-picker?tab=readme-ov-file

**Comment by mape** [comment]
I had a quick look at this and it seems to work fine for the initial part of the flow but breaks on restart.
Not sure what I could do on my end to fix it.

https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/d708320d-778b-46d7-bcb1-2ba18d439fe7

**Comment by rcdailey** [comment]
@mape your video isn't working anymore... some text based instructions would be helpful as I've had no luck understanding what's going on in the videos.

What was your workaround?
