### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'nodes')

### ISSUE THREAD

**Issue by mizukarada** [mape/ComfyUI-mape-Helpers#2]
On https://github.com/mape/ComfyUI-mape-Helpers/commit/f872692636e8d02333eda42caf289157530f290d
No other extensions installed.
Default ComfyUI workflow
Browser: Edge
OS: macOS Ventura 13.5.1

Got this error in the browser:
```console
Uncaught TypeError: Cannot read properties of undefined (reading 'nodes')
 at mape-helpers.js:1:51304
```
which points to:
```js
            for (const w of d.nodes) {
                if (w.type !== "PrimitiveNode")
                    continue;
                const b = oe(w.id);
                if (b)
                    for (const [A,y] of (w.widgets_values ?? []).entries())
                        b.widgets[A].value = y
            }
```

It seems to be solved if i put `if (d)` before that `for` loop, however, i'm not sure why but i can't get my ui to be the same as the top left and top right of the image in the readme?

![mape's ComfyUI helpers](https://comfyui.ma.pe/github.jpg)

**Comment by mape** [comment]
I pushed an update that hopefully fixes your issue.

To add a variable to the top bar you need to expand a `set` node and check the `Tweak` checkbox.

For images to show up in the image preview (which you open by clicking 🖥️ in the top right) a `get` node needs to be hooked up to a `PreviewImage` or a `SaveImage` node.

![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/f2dacb36-8558-4200-b84f-f24a6002179b)

![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/e8c050ef-33dc-42c7-acc2-009e23916047)

**Comment by mizukarada** [comment]
Oh I had to convert it to those nodes first. Thanks!
