### ISSUE TITLE
Feature request: Shortcut for Batch Rename

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [mape/ComfyUI-mape-Helpers#20]
I would love CTRL + LMB or SHIFT + LMB on a variable to rename it with the `Batch rename variables` feature.
I couldn't figure out how it was done until the instruction on the https://comfyui.ma.pe/-page got to that specific feature.

**Comment by mape** [comment]
I added the ability to shift + double click to rename in the latest release.
litegraph.js didn't like triggering events for CTRL clicking.

Not quite what you asked for but hopefully it is still useful.

**Comment by MNeMoNiCuZ** [comment]
A shame that it's not supported better, but not a big deal :)
