### ISSUE TITLE
incompatible with StableSwarmUI

### ISSUE THREAD

**Issue by marshmallowking** [mape/ComfyUI-mape-Helpers#28]
Your plugin is super useful and i would love to keep using it, however, it appears to be incompatible with StableSwarmUI.
The nodes don't load properly and a lot of functionality stops working, shift-clicking nodes for instance, also the workflows error out when queuing them.

**Comment by mape** [comment]
Unfortunately I won't have the time to look at this.

The ComfyUI frontend ecosystem is a bit of a wild wild west and my plugin "breaks" a pretty fundamental part (links) that other plugins sometimes use to fetch dynamic data.
