### ISSUE TITLE
Manager position, other info covered by Mape title bar - Why does it need to go all the way across the whole screen? 

### ISSUE THREAD

**Issue by EricRollei** [mape/ComfyUI-mape-Helpers#29]
Thank you for your mape helpers.  They are excellent.    

It's a minor thing but why does the mape bar need to cross the entire screen when the only active parts are on the right side?   Left side covers my other info window (red outlined box) which shows what node is active during a run, and also at the moment I've got my manager stuck in a position that I can't get to because the Mape bar is covering it. and I can only grab the manager from the top. Can't access settings. 

![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/97568200/6c3fea3a-30f4-4cec-a71c-a2c9929a2b4a)

**Comment by mape** [comment]
Added a button to toggle the top bar in the latest release. Hope it helps.

https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/fd636564-8a84-4cda-9c90-4d5b9edf840e
