### ISSUE TITLE
Errors with wireless links

### ISSUE THREAD

**Issue by AlexD81** [mape/ComfyUI-mape-Helpers#3]
Hi, I'm affraid in real projects it appears to be too buggy. Workflow may sudenly stop working throwing errors.  Restart comfy and UI helps temporarely, but then it happerns again.
https://snipboard.io/mW79Ue.jpg
Here I just changed  checkpoint model,   workflow was without errors before changing,   but after changing  it throwing errors,  and I see  wireless links got broken.  This time restarting comfy doens't helps.
On my side I think I do everything right,  XL  checkpoint changes to another XL, it should not cause any problems.

**Comment by mape** [comment]
Hi, do you have a workflow where you can reproduce the issue?

**Comment by AlexD81** [comment]
My common workflow is big....  Hard to send something, becouse errors are random, and on random places.  I'll try to figure out.     But is it normal that some wireless links in workflow are insible even if corresponding wireless node is selected? Like in my previous screenshot.   https://snipboard.io/mW79Ue.jpg   
They are working, if to open previously saved workflow,  but my guess so far that the errors are related with them

**Comment by mape** [comment]
Invisible? When you select a `set` node you should see a link going to the corresponding `get` node.
Can you double check that they have the same name? They are case sensitive.

**Comment by AlexD81** [comment]
yes, sure, they have the same name.  But as you may see on screenshot it's selected  but link is not visible. But what is interesting, the link **is** working.  But sometimes stops working.  Ill write later when I find a way how to reproduce, it's very random. Current guess, the errors somehow related with these invisible wireless links when changing checkpoints

**Comment by mape** [comment]
Are you still encountering problems after upgrading to the latest version?

**Comment by AlexD81** [comment]
> Are you still encountering problems after upgrading to the latest version?
didn't get errors for 1 working day,  I guess, it's working now,  probably need more time to be completely sure.  I will write if i found them. Thanks for your work!
