### ISSUE TITLE
can i hide it

### ISSUE THREAD

**Issue by guahunyo** [mape/ComfyUI-mape-Helpers#31]
![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/18573180/50443f90-0f5c-4912-a840-e75ed5d00c04)

**Comment by mape** [comment]
You can toggle the bar by clicking the section in the top right:

https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/48a55f8e-e1c6-4281-9240-842de88fc397
