### ISSUE TITLE
Feature Request: Floating prompt tweak panel

### ISSUE THREAD

**Issue by naiyansui2023** [mape/ComfyUI-mape-Helpers#4]
prompt tweaking, if it could float, it could move, that would be really cool.

**Comment by mape** [comment]
I'll have a look and see if it is easy to add.

**Comment by mape** [comment]
Pushed a new build that lets you pin/unpin the prompt tweak sections.

Let me know if you encounter any bugs.

https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/b8d16c68-f1ea-4209-b4b4-4864ba998cec

**Comment by naiyansui2023** [comment]
It's really cool, I like it very much, thank you very much.
