### ISSUE TITLE
Image preview

### ISSUE THREAD

**Issue by Tobe2d** [mape/ComfyUI-mape-Helpers#7]
Hi, 1st I would like to thank you for the great and very usefull code.

2nd, I have an strange issue while trying to use the Image preview.

When I click on this icon:
![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/4099839/86936371-be2b-4994-b074-7a9c78253df4)

it open this:
![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/4099839/e55c1b20-c93a-4967-9683-a270b7931ddc)

I have trested it with shift and without and it open the same window. what am I missing to get the Image preview like your demo?

**Comment by mape** [comment]
Hey, are the instructions in the image you posted not working for you?

**Comment by Tobe2d** [comment]
Thanks for the reply, as mentioned before it is opining the 2nd screenshot I post above. it does not look like the video you share.
I am mainly intersted in flipbook

**Comment by mape** [comment]
The picture is telling you what to do.
You need to have a variable connected to a preview/save node and enable `tweak`.

**Comment by Tobe2d** [comment]
OMG!! Okay it works fine now. I was drunk or something.

Thank you again!!!!
