### ISSUE TITLE
Compatibility Issue with (repo:pythongosssss/ComfyUI-Custom-Scripts)'s AutoComplete. CPU Spike and ComfyUI stutter.

### ISSUE THREAD

**Issue by GitGoodOrGitGone** [mape/ComfyUI-mape-Helpers#8]
Hello, Fist I want to say that I really enjoy your wireless nodes, duel monitor gallery, and "command center" like menu bar with all those goodies, LOVE EM.
Now the issue.

(ComfyUI-Custom-Scripts) has a AutoComplete feature (I have about 161k custom tags.) and works smoothly without any noticeable CPU usage, however when (Mape-Helper) is enabled and I start to type/ query tags I find ComfyUI lags HARD with stuttering as CPU usage ramps up on two cores maxing out. 
This issue persists even on a empty workspace with just a normal unpinned CLIP encode node with Autocomplete enabled.
To clarify: CPU Maxing and UI Stutter only while typing in a field with Autocomplete, it's trying do something to the whole list and freaking out.

In the meantime I just disable Autocomplete to fix the issue temporarily while doing low priority work in favor of using (Mape-Helpers). I just love it that much.
 Heck I'm kinda fine putting up with the crazy UI stutter if it was just UI bugs but two CPU cores maxing out just imputing a character is crazy!
 
 
-GitGood

**Comment by mape** [comment]
Hey, can you try disabling fuzzy search in top right ⚙️settings and see if that helps?

![image](https://github.com/mape/ComfyUI-mape-Helpers/assets/25655/6cce7d6d-9d2f-4bb0-a038-9d27072d0ae4)

**Comment by GitGoodOrGitGone** [comment]
That fixed the issue!

And for anyone who reads this in the future, remember to refresh the page after you disable (Fuzzy Search).

Thanks, Mape!

**Comment by xueqing0622** [comment]
It works, thx
