### ISSUE TITLE
About the situation where the text cannot be recognized

### ISSUE THREAD

**Issue by RainEmy** [mape/ComfyUI-mape-Helpers#9]
![%7BF7904848-9C19-46b8-A2F7-2E5C6C1DB807%7D](https://github.com/mape/ComfyUI-mape-Helpers/assets/112817003/bc9c3eaf-9fe0-44c5-92a1-ea3d07612ce6)
Thank you very much for open sourcing such a great project. Here I would like to report a small problem in use.
I use translation nodes. If I use "tweak" at this time, the first word of the translation node will be sent up. When using weight control, the first word of the translation node will be changed...

**Comment by mape** [comment]
Unfortunately I doubt this will ever work since the tweak panel needs to set the value after it has been modified.
That isn't possible if the input is dynamically generated by another node.

Your best bet would be to copy paste the translated output into a basic string node.
